### ISSUE TITLE
You alright?

### ISSUE THREAD

**Issue by yodabird19** [ccmap/data#53]
Hi Gjum,
You've been no-contact for a while, despite being visibly active on Github. It's fine if you can't be around, but the sudden, unwarned disappearance is somewhat unnerving. Is everything okay?
PS: thanks orange wizard for this idea :glad:

**Comment by Gjum** [comment]
Thanks for reminding me of the open PRs. I'm fine, I've just been taking a break from civ for now.
I've given @RedDevel2 permissions to merge PRs and push other updates, I'll leave this open in case you need anything else.

**Comment by RedDevel2** [comment]
Are you sure you gave me the permissions? cause I don't seem to be able to merge yet.

**Comment by RedDevel2** [comment]
Ah yes, that was it., thank you.

**Comment by Metriximor** [comment]
@Gjum I'm looking into making wikibots that automatically update the civwiki, can I get perms on this repo too?

**Comment by RedDevel2** [comment]
I'm trying to turn the settlement spreadsheet into json data. But it seems (from googling) that the command needed is a linux thing, So I can't run it. Is there another command/way?

**Comment by Metriximor** [comment]
@Gjum heya, I'd like to setup some wiki secrets so I can setup an automatic python bot to update the wiki, u there?

**Comment by Gjum** [comment]
@Metriximor I've added you as maintainer https://github.com/ccmap/data/invitations

**Comment by Metriximor** [comment]
Thanks
